source 'https://rubygems.org'

gem 'rails', '4.0.2'
gem 'pg'
gem 'pry'
gem 'rails_12factor'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 1.2'
gem 'rspec-rails'
gem 'ruby_spark'
gem 'simple_form'
gem 'twilio-ruby'
gem 'factory_girl_rails'
